(()=>{
'use strict';
const $=id=>document.getElementById(id);
const F={enabled:true,loading:false,points:[],timer:null,canvas:null,ctx:null,raf:0,particles:[],bounds:null};
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function map(){return window.__rainGuardWindyMap||window.__windyMap||document.querySelector('#windyMap')?window.S?.map:null}
function getMap(){return window.__RG_MAP||(window.__RG_MAP=(()=>{try{return document.querySelector('#windyMap')?window.__rainGuardMap:null}catch{return null}})())}
function toast(m){if(typeof window.__rainGuardToast==='function')window.__rainGuardToast(m);else{let e=$('wgToast');if(e){e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}}}
function getLeafletMap(){return window.RG_MAP||window.rainGuardMap||window.__RG_LEAFLET_MAP||null}
function init(){const app=$('windyApp');if(!app)return setTimeout(init,300);const mapEl=$('windyMap');if(!mapEl)return;F.canvas=document.createElement('canvas');F.canvas.className='flow-canvas';mapEl.appendChild(F.canvas);F.ctx=F.canvas.getContext('2d');addFlowButton();setTimeout(()=>{hookMap();resize();fetchFlow()},600);window.addEventListener('resize',resize)}
function hookMap(){const m=window.__RG_LEAFLET_MAP||window.rainGuardLeaflet||window.__windyLeaflet; if(m){F.map=m;['move','zoom','resize'].forEach(ev=>m.on(ev,()=>{resize();seed()}));return}setTimeout(hookMap,500)}
function resize(){if(!F.canvas)return;const r=$('windyMap').getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);F.canvas.width=r.width*d;F.canvas.height=r.height*d;F.canvas.style.width=r.width+'px';F.canvas.style.height=r.height+'px';F.ctx?.setTransform(d,0,0,d,0,0);F.w=r.width;F.h=r.height}
function addFlowButton(){if($('flowBtn'))return;const actions=document.querySelector('.windy-actions');if(!actions)return;const b=document.createElement('button');b.id='flowBtn';b.className='windy-action flow-action';b.innerHTML='➜ Flow<br><span>India wind & cyclone</span>';b.onclick=()=>{F.enabled=!F.enabled;b.classList.toggle('active',F.enabled);if(F.enabled){fetchFlow();toast('🌬️ India flow animation ON')}else clearCanvas()};actions.appendChild(b)}
function bbox(){if(!F.map)return null;const c=F.map.getCenter(),z=F.map.getZoom();const span=Math.max(3,18/Math.pow(1.35,z-5));return{lat0:c.lat-span*.65,lat1:c.lat+span*.65,lon0:c.lng-span,lon1:c.lng+span}}
async function fetchFlow(){if(!F.enabled||F.loading)return;F.loading=true;try{const b=bbox();if(!b){F.loading=false;return}const n=6,lat=[],lon=[];for(let j=0;j<n;j++)for(let i=0;i<n;i++){lat.push(b.lat0+(b.lat1-b.lat0)*j/(n-1));lon.push(b.lon0+(b.lon1-b.lon0)*i/(n-1))}const u=`https://api.open-meteo.com/v1/forecast?latitude=${lat.join(',')}&longitude=${lon.join(',')}&current=wind_speed_10m,wind_direction_10m,pressure_msl&timezone=auto`;const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json();F.points=(Array.isArray(d)?d:[d]).map((x,i)=>({lat:lat[i],lon:lon[i],speed:+(x.current?.wind_speed_10m||0),dir:+(x.current?.wind_direction_10m||0),p:+(x.current?.pressure_msl||1013)}));findLow();seed();}catch(e){toast('Flow data unavailable')}finally{F.loading=false}}
function findLow(){if(!F.points.length)return;let low=F.points.reduce((a,b)=>b.p<a.p?b:a);F.low=low}
function project(lat,lon){if(!F.map)return null;const p=F.map.latLngToContainerPoint([lat,lon]);return{x:p.x,y:p.y}}
function nearest(x,y){let best=null,bd=1e9;for(const p of F.points){const q=project(p.lat,p.lon);if(!q)continue;const d=(q.x-x)**2+(q.y-y)**2;if(d<bd){bd=d;best=p}}return best}
function seed(){if(!F.enabled||!F.w)return;F.particles=[];for(let i=0;i<170;i++){const x=Math.random()*F.w,y=Math.random()*F.h,p=nearest(x,y)||{speed:10,dir:0};F.particles.push({x,y,life:Math.random()*100,max:55+Math.random()*90,speed:Math.max(1.2,p.speed*.045),dir:p.dir*Math.PI/180,alpha:.35+Math.random()*.45})}draw();}
function draw(){if(!F.ctx||!F.enabled)return;clearCanvas();for(const a of F.particles){const p=nearest(a.x,a.y);if(p)a.dir=p.dir*Math.PI/180;const rad=a.dir+Math.PI;const dx=Math.sin(rad)*a.speed,dy=-Math.cos(rad)*a.speed;a.x+=dx;a.y+=dy;a.life--;if(a.x<-20||a.y<-20||a.x>F.w+20||a.y>F.h+20||a.life<=0){a.x=Math.random()*F.w;a.y=Math.random()*F.h;a.life=a.max}const head=8;F.ctx.save();F.ctx.globalAlpha=a.alpha;F.ctx.strokeStyle='#fff';F.ctx.lineWidth=1.8;F.ctx.beginPath();F.ctx.moveTo(a.x-dx*2,a.y-dy*2);F.ctx.lineTo(a.x,a.y);F.ctx.stroke();F.ctx.beginPath();F.ctx.moveTo(a.x,a.y);F.ctx.lineTo(a.x-dx*head/Math.max(1,Math.abs(dx)+Math.abs(dy))-dy*.45,a.y-dy*head/Math.max(1,Math.abs(dx)+Math.abs(dy))+dx*.45);F.ctx.moveTo(a.x,a.y);F.ctx.lineTo(a.x-dx*head/Math.max(1,Math.abs(dx)+Math.abs(dy))+dy*.45,a.y-dy*head/Math.max(1,Math.abs(dx)+Math.abs(dy))-dx*.45);F.ctx.stroke();F.ctx.restore()}drawLow();F.raf=requestAnimationFrame(draw)}
function drawLow(){if(!F.low||!F.map)return;const q=project(F.low.lat,F.low.lon);if(!q)return;F.ctx.save();F.ctx.translate(q.x,q.y);const t=performance.now()/900;F.ctx.rotate(t*.05);F.ctx.globalAlpha=.6;F.ctx.strokeStyle='#fff';F.ctx.lineWidth=2;for(let r=9;r<32;r+=8){F.ctx.beginPath();F.ctx.arc(0,0,r,0,Math.PI*1.55);F.ctx.stroke()}F.ctx.fillStyle='#ffdf4d';F.ctx.font='700 12px Inter,system-ui';F.ctx.textAlign='center';F.ctx.fillText('LOW',0,-38);F.ctx.restore()}
function clearCanvas(){if(F.ctx)F.ctx.clearRect(0,0,F.w||0,F.h||0)}
window.addEventListener('beforeunload',()=>cancelAnimationFrame(F.raf));
setTimeout(init,400);
})();
