(()=>{
'use strict';
const $=id=>document.getElementById(id);
const F={enabled:true,mode:'flow',loading:false,points:[],canvas:null,ctx:null,raf:0,particles:[],low:null,w:0,h:0};
function toast(m){if(typeof window.__rainGuardToast==='function')window.__rainGuardToast(m);else{const e=$('wgToast');if(e){e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}}}
function coords(){const t=$('windyCoords')?.textContent||'13.0827, 80.2707',m=t.match(/(-?\d+(?:\.\d+)?)[, ]+(-?\d+(?:\.\d+)?)/);return m?{lat:+m[1],lon:+m[2]}:{lat:13.0827,lon:80.2707}}
function cardinal(){const t=($('windDir')?.textContent||'').toUpperCase();const m=t.match(/(N|NE|E|SE|S|SW|W|NW)\b/);return m?m[1]:'E'}
function angle(){return ({N:0,NE:45,E:90,SE:135,S:180,SW:225,W:270,NW:315}[cardinal()]||90)+180}
function init(){const app=$('windyApp'),map=$('windyMap');if(!app||!map)return setTimeout(init,300);F.canvas=document.createElement('canvas');F.canvas.className='flow-canvas';map.appendChild(F.canvas);F.ctx=F.canvas.getContext('2d');addControls();resize();window.addEventListener('resize',resize);fetchField();setInterval(fetchField,10*60*1000)}
function addControls(){const actions=document.querySelector('.windy-actions');if(!actions||$('flowBtn'))return;const b=document.createElement('button');b.id='flowBtn';b.className='windy-action flow-action active';b.innerHTML='➜ Flow<br><span>India wind field</span>';b.onclick=()=>{F.mode=F.mode==='flow'?'vortex':'flow';b.classList.toggle('vortex',F.mode==='vortex');b.innerHTML=F.mode==='vortex'?'🌀 Cyclone flow<br><span>pressure + wind</span>':'➜ Flow<br><span>India wind field</span>';seed();toast(F.mode==='vortex'?'🌀 Vortex/cyclone flow view ON':'🌬️ Wind direction flow ON')};actions.appendChild(b)}
function resize(){if(!F.canvas)return;const r=$('windyMap').getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);F.w=r.width;F.h=r.height;F.canvas.width=r.width*d;F.canvas.height=r.height*d;F.canvas.style.width=r.width+'px';F.canvas.style.height=r.height+'px';F.ctx.setTransform(d,0,0,d,0,0);seed()}
async function fetchField(){if(F.loading)return;F.loading=true;try{const c=coords(),n=5,span=.9,lat=[],lon=[];for(let y=0;y<n;y++)for(let x=0;x<n;x++){lat.push(c.lat-span+2*span*y/(n-1));lon.push(c.lon-span*1.4+2*span*1.4*x/(n-1))}const u=`https://api.open-meteo.com/v1/forecast?latitude=${lat.join(',')}&longitude=${lon.join(',')}&current=wind_speed_10m,wind_direction_10m,pressure_msl&timezone=auto`;const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json();F.points=(Array.isArray(d)?d:[d]).map((x,i)=>({lat:lat[i],lon:lon[i],speed:+(x.current?.wind_speed_10m||0),dir:+(x.current?.wind_direction_10m||0),p:+(x.current?.pressure_msl||1013)}));F.low=F.points.reduce((a,b)=>b.p<a.p?b:a,F.points[0]);seed()}catch{toast('Wind-flow data unavailable')}finally{F.loading=false}}
function seed(){if(!F.w||!F.enabled)return;F.particles=[];for(let i=0;i<190;i++)F.particles.push({x:Math.random()*F.w,y:Math.random()*F.h,life:Math.random()*100,max:70+Math.random()*80,s:1.1+Math.random()*2,a:.25+Math.random()*.55});cancelAnimationFrame(F.raf);draw()}
function fieldAt(x,y){if(!F.points.length)return{dir:angle(),speed:10};const c=coords(),gx=(x/F.w-.5)*2.8,gy=(y/F.h-.5)*2.0;let best=F.points[0],bd=1e9;for(const p of F.points){const px=(p.lon-c.lon)/1.26,py=(p.lat-c.lat)/.9,d=(px-gx)**2+(py-gy)**2;if(d<bd){bd=d;best=p}}return best}
function draw(){if(!F.enabled||!F.ctx)return;F.ctx.clearRect(0,0,F.w,F.h);for(const a of F.particles){const p=fieldAt(a.x,a.y),base=(p.dir+180)*Math.PI/180;let dx,dy;if(F.mode==='vortex'){const cx=F.w/2,cy=F.h/2,rx=a.x-cx,ry=a.y-cy,t=Math.atan2(ry,rx)+Math.PI/2;dx=Math.cos(t)*a.s;dy=Math.sin(t)*a.s}else{dx=Math.sin(base)*a.s*(1+p.speed/25);dy=-Math.cos(base)*a.s*(1+p.speed/25)}a.x+=dx;a.y+=dy;a.life--;if(a.life<0||a.x<-30||a.y<-30||a.x>F.w+30||a.y>F.h+30){a.x=Math.random()*F.w;a.y=Math.random()*F.h;a.life=a.max}const len=9,mag=Math.max(1,Math.hypot(dx,dy));F.ctx.save();F.ctx.globalAlpha=a.a;F.ctx.strokeStyle='#fff';F.ctx.lineWidth=1.7;F.ctx.beginPath();F.ctx.moveTo(a.x-dx*2,a.y-dy*2);F.ctx.lineTo(a.x,a.y);F.ctx.stroke();F.ctx.beginPath();F.ctx.moveTo(a.x,a.y);F.ctx.lineTo(a.x-dx/mag*len-dy/mag*4,a.y-dy/mag*len+dx/mag*4);F.ctx.moveTo(a.x,a.y);F.ctx.lineTo(a.x-dx/mag*len+dy/mag*4,a.y-dy/mag*len-dx/mag*4);F.ctx.stroke();F.ctx.restore()}if(F.mode==='vortex')drawVortex();F.raf=requestAnimationFrame(draw)}
function drawVortex(){const cx=F.w/2,cy=F.h/2,t=performance.now()/800;F.ctx.save();F.ctx.translate(cx,cy);F.ctx.rotate(t*.18);F.ctx.strokeStyle='#fff';F.ctx.globalAlpha=.55;F.ctx.lineWidth=2;for(let r=24;r<80;r+=18){F.ctx.beginPath();F.ctx.arc(0,0,r,.2,Math.PI*1.55);F.ctx.stroke()}F.ctx.fillStyle='#ffd43b';F.ctx.font='700 12px Inter,system-ui';F.ctx.textAlign='center';F.ctx.fillText('LOW PRESSURE / FLOW',0,-92);F.ctx.restore()}
setTimeout(init,500);
})();
