/* RainGuard: browser-safe IMD/RMC layer.
   GitHub Pages reads the immutable snapshot generated by GitHub Actions.
   The UI never claims a live official feed exists when the upstream API
   was unavailable; it shows the actual snapshot status instead. */
(function () {
  function esc(v) {
    return String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  }

  function textFrom(value, keys) {
    if (value == null) return '';
    if (typeof value === 'string' || typeof value === 'number') return String(value);
    if (Array.isArray(value)) {
      for (const item of value) { const found = textFrom(item, keys); if (found) return found; }
      return '';
    }
    if (typeof value === 'object') {
      for (const key of keys) {
        if (value[key] != null && String(value[key]).trim()) return String(value[key]);
      }
      for (const item of Object.values(value)) { const found = textFrom(item, keys); if (found) return found; }
    }
    return '';
  }

  function findLocationText(value, label) {
    const wanted = String(label || '').toLowerCase().split(',')[0].trim();
    const hints = ['tiruvannamalai', 'thiruvannamalai', 'polur'];
    const raw = JSON.stringify(value || '').toLowerCase();
    const matchHint = hints.find(x => raw.includes(x));
    if (!matchHint && !wanted) return '';

    function walk(v) {
      if (Array.isArray(v)) {
        for (const item of v) { const found = walk(item); if (found) return found; }
      } else if (v && typeof v === 'object') {
        const blob = JSON.stringify(v).toLowerCase();
        if ((wanted && blob.includes(wanted)) || (matchHint && blob.includes(matchHint))) {
          const found = textFrom(v, ['warning','Warning','message','Message','district_warning','districtWarning','nowcast','Nowcast','description','Description','text','Text','title','Title']);
          if (found) return found;
        }
        for (const item of Object.values(v)) { const found = walk(item); if (found) return found; }
      }
      return '';
    }
    return walk(value);
  }

  function updatedLabel(iso) {
    if (!iso) return 'Snapshot time unavailable';
    try {
      return `Updated ${new Date(iso).toLocaleString([], {year:'numeric', month:'short', day:'numeric', hour:'numeric', minute:'2-digit', hour12:true})}`;
    } catch (_) { return 'Snapshot time unavailable'; }
  }

  function statusText(status) {
    const values = Object.values(status || {});
    if (values.includes('ok') || values.includes('rss-fallback')) return 'Official IMD/RMC snapshot refreshed.';
    return 'Official IMD/RMC APIs are unavailable from the refresh runner.';
  }

  window.loadImdData = async function (lat, lon, label) {
    const grid = document.getElementById('imdGrid');
    const warning = document.getElementById('imdWarning');
    if (!grid || !warning) return;

    try {
      const response = await fetch(`./imd-data.json?v=${Date.now()}`, { cache: 'no-store' });
      if (!response.ok) throw new Error('IMD snapshot unavailable');
      const data = await response.json();
      const status = data.status || {};

      const current = data.current && !data.current.error ? data.current : null;
      const nowcast = data.nowcast && !data.nowcast.error ? data.nowcast : null;
      const districtWarning = data.warning && !data.warning.error ? data.warning : null;

      const currentText = current
        ? (textFrom(current, ['temp','temperature','Temp','Temperature']) || textFrom(current, ['weather','Weather','description','Description']) || 'Official feed available')
        : 'No current feed';
      const nowcastText = findLocationText(nowcast, label) || (status.nowcast === 'rss-fallback' ? 'Official RSS fallback available' : nowcast ? 'Official feed available' : 'No nowcast feed');
      const warningText = findLocationText(districtWarning, label) || (status.warning === 'rss-fallback' ? 'Official RSS fallback available' : districtWarning ? 'Official feed available' : 'No warning feed');

      grid.innerHTML = `
        <div class="imd-item"><span>IMD Current</span><strong>${esc(currentText).slice(0,110)}</strong></div>
        <div class="imd-item"><span>RMC Nowcast</span><strong>${esc(nowcastText).slice(0,110)}</strong></div>
        <div class="imd-item"><span>District Warning</span><strong>${esc(warningText).slice(0,110)}</strong></div>`;

      const apiLimited = !current && status.nowcast !== 'ok' && status.warning !== 'ok';
      warning.className = apiLimited ? 'imd-warning yellow' : 'imd-warning green';
      warning.innerHTML = `${apiLimited ? '⚠️' : '🇮🇳'} <strong>${esc(statusText(status))}</strong> · ${esc(updatedLabel(data.updated_at))}${status.rss === 'ok' ? ' · RSS fallback enabled' : ''}`;
    } catch (_) {
      grid.innerHTML = `
        <div class="imd-item"><span>IMD Current</span><strong>Snapshot unavailable</strong></div>
        <div class="imd-item"><span>RMC Nowcast</span><strong>Snapshot unavailable</strong></div>
        <div class="imd-item"><span>District Warning</span><strong>Snapshot unavailable</strong></div>`;
      warning.className = 'imd-warning yellow';
      warning.textContent = 'Official IMD/RMC snapshot is unavailable. Refresh after the scheduled GitHub Actions update.';
    }
  };
})();
