(()=>{
const $=id=>document.getElementById(id);
const state={lat:13.0827,lon:80.2707,city:'Chennai',data:null,hour:0,playing:false,timer:null,map:null,marker:null};
function loadLeaflet(){return new Promise((resolve,reject)=>{if(window.L)return resolve();if(!document.querySelector('link[data-leaflet]')){const l=document.createElement('link');l.rel='stylesheet';l.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';l.dataset.leaflet='1';document.head.appendChild(l)}const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
function inject(){if(document.getElementById('windyApp'))return;const app=document.createElement('div');app.id='windyApp';app.className='windy-app';app.innerHTML=`<div id="windyMap" class="windy-map"></div><div id="windyParticles" class="windy-particles"></div><div class="windy-header"><div class="windy-mainline"><div><div class="wind-label">Wind</div><span id="windSource" class="wind-source">ECMWF, Surface</span></div><strong id="windValue" class="wind-value">— kt</strong><strong id="windDir" class="wind-dir">← E</strong><span class="windy-info">ⓘ</span></div><div class="windy-actions"><button class="windy-action forecast" id="forecastBtn">⚙️&nbsp; Forecast<br><span>for this point</span></button><button class="windy-action support">♛&nbsp; Support<br><span>Windy.com</span></button><button class="windy-action">▥&nbsp; Distance<br><span>&amp; route plan</span></button><button class="windy-action">▥&nbsp; Satellite<br><span>weather view</span></button></div><button id="windyClose" class="windy-close">×</button></div><div class="windy-map-crosshair">− · −<br>│</div><div class="windy-place"><strong id="windyPlace">Chennai</strong><span id="windyCoords">13.0827, 80.2707</span></div><div class="windy-side"><button id="windyHome">⌂</button><button id="windySearch">⌕</button><button id="windyPin">📌</button><button id="windyFav">♥</button><button id="windyAlert" class="danger">☰</button></div><button id="windyPlay" class="windy-play">▶</button><div class="windy-bottom"><div id="windyBubble" class="windy-time-bubble">11 AM</div><div id="windyDays" class="windy-days"><div class="windy-day active">Tuesday 18</div><div class="windy-day">Wednesday 19</div><div class="windy-day">Thursday 20</div></div><div class="windy-scale"><span class="windy-unit">kt</span><div class="windy-scale-labels"><span>0</span><span>5</span><span>10</span><span>20</span><span>30</span><span>40</span><span>60</span></div></div></div><div id="windyLoading" class="windy-loading">Loading live weather…</div>`;document.body.appendChild(app);bind();makeParticles()}
function bind(){$('windyClose').onclick=()=>document.getElementById('windyApp')?.remove();$('windyHome').onclick=()=>{if(state.map)state.map.setView([state.lat,state.lon],5);};$('windySearch').onclick=()=>{const q=prompt('Search city');if(q)searchCity(q)};$('windyPin').onclick=()=>navigator.geolocation?.getCurrentPosition(p=>setLocation(p.coords.latitude,p.coords.longitude));$('windyFav').onclick=()=>alert('Location saved locally');$('windyAlert').onclick=()=>alert('Weather layers are live. Severe signals are shown in RainGuard below.');$('forecastBtn').onclick=()=>alert('Forecast for this point is shown on the timeline below.');$('windyPlay').onclick=()=>{state.playing=!state.playing;$('windyPlay').textContent=state.playing?'❚❚':'▶';clearInterval(state.timer);if(state.playing)state.timer=setInterval(()=>{state.hour=(state.hour+1)%12;render()},900)};}
function makeParticles(){const p=$('windyParticles');for(let i=0;i<90;i++){const x=document.createElement('i');x.className='windy-particle';x.style.left=`${Math.random()*100}%`;x.style.top=`${Math.random()*100}%`;x.style.setProperty('--dur',`${3+Math.random()*5}s`);x.style.setProperty('--dx',`${-160+Math.random()*320}px`);x.style.setProperty('--rot',`${-35+Math.random()*70}deg`);x.style.animationDelay=`-${Math.random()*6}s`;p.appendChild(x)}}
function setLocation(lat,lon,city){state.lat=Number(lat);state.lon=Number(lon);if(city)state.city=city;$('windyPlace').textContent=state.city;$('windyCoords').textContent=`${state.lat.toFixed(4)}, ${state.lon.toFixed(4)}`;if(state.map){state.map.setView([state.lat,state.lon],5);if(state.marker)state.marker.setLatLng([state.lat,state.lon]);else state.marker=L.circleMarker([state.lat,state.lon],{radius:7,color:'#fff',weight:3,fillColor:'#e7a800',fillOpacity:1}).addTo(state.map)}}
async function searchCity(city){try{const r=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(city)}&count=1&language=en&format=json`);const d=await r.json();if(!d.results?.length)return alert('City not found');const x=d.results[0];setLocation(x.latitude,x.longitude,`${x.name}${x.country?`, ${x.country}`:''}`);await load()}catch(e){alert('Unable to search city')}}
async function load(){try{const url=`https://api.open-meteo.com/v1/forecast?latitude=${state.lat}&longitude=${state.lon}&current=temperature_2m,wind_speed_10m,wind_direction_10m,weather_code&hourly=temperature_2m,precipitation_probability,precipitation,wind_speed_10m,wind_direction_10m,weather_code&forecast_days=2&timezone=auto`;const r=await fetch(url,{cache:'no-store'});state.data=await r.json();state.hour=0;render();$('windyLoading').classList.add('hidden')}catch(e){$('windyLoading').textContent='Live weather unavailable'}}
function idx(){if(!state.data)return 0;const now=new Date(state.data.current.time).getTime();let i=0;for(let j=0;j<state.data.hourly.time.length;j++){if(new Date(state.data.hourly.time[j]).getTime()<=now)i=j;else break}return Math.min(i+state.hour,state.data.hourly.time.length-1)}
function render(){if(!state.data)return;const i=idx(),h=state.data.hourly,c=state.data.current;const wind=Number(h.wind_speed_10m?.[i]??c.wind_speed_10m??0),deg=Number(h.wind_direction_10m?.[i]??c.wind_direction_10m??0),kt=wind*.539957;const dirs=['N','NE','E','SE','S','SW','W','NW'];const dir=dirs[Math.round(deg/45)%8];$('windValue').textContent=`${Math.round(kt)} kt`;$('windDir').textContent=`← ${dir}`;$('windyBubble').textContent=fmt(h.time[i]);document.querySelectorAll('.windy-day').forEach((x,n)=>x.classList.toggle('active',n===0));if(state.map&&state.marker)state.marker.setLatLng([state.lat,state.lon]);}
function fmt(x){const m=String(x).match(/T(\d{2}):(\d{2})/);if(!m)return'—';let h=Number(m[1]);const ap=h>=12?'PM':'AM';h=h%12||12;return`${h} ${ap}`}
async function init(){inject();try{await loadLeaflet();state.map=L.map('windyMap',{zoomControl:false,attributionControl:true}).setView([state.lat,state.lon],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap contributors'}).addTo(state.map);setLocation(state.lat,state.lon,state.city);navigator.geolocation?.getCurrentPosition(p=>setLocation(p.coords.latitude,p.coords.longitude),()=>{}, {enableHighAccuracy:true,timeout:7000,maximumAge:60000});await load()}catch(e){$('windyLoading').textContent='Map service unavailable';}}
init();setInterval(()=>{if(document.getElementById('windyApp'))load()},15*60*1000);
})();
